### ISSUE TITLE
Check that it works using cmd - on Windows

### ISSUE THREAD

**Issue by kazazor** [kazazor/git-pre-commit#3]

**Comment by kazazor** [comment]
This also effects #4

**Comment by kazazor** [comment]
Could try and see if it can e solved like in here:
https://github.com/ben-eb/gulp-symlink/pull/31

**Comment by kazazor** [comment]
Instead what we'll do is just use a simple copy of the files instead of using symlinks

**Comment by felquis** [comment]
I'm using PowerShell, and once `npm install` I get this error:

```

> git-pre-commit@2.1.4 postinstall C:\Users\username\workplace\project\node_modules\git-pre-commit
> gulp hooks:install

fs.js:39
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:39:5
    at req_ (C:\Users\username\workplace\project\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\username\workplace\project\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\username\workplace\project\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
```

node -v 14.x
