### ISSUE TITLE
Windows error

### ISSUE THREAD

**Issue by okeydoke** [kazazor/git-pre-commit#33]
Hi there ,
Trying to get the package working but getting the following error in Windows

```
module.js:474
    throw err;
    ^

Error: Cannot find module '.\pre-commit-utils\git-manager'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\dev\bd-events\.git\hooks\pre-commit.js:9:20)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
```

Any ideas? 
Have 
`"precommit": "npm test",` in my package.json file

**Comment by kazazor** [comment]
That will be part of version `2.1.3` thanks to @Goldob who fixed it :)

**Comment by kazazor** [comment]
@okeydoke , just published it now - please have a look
